version: '2'

services:
  nginx-pagespeed:
    container_name: nginx-pagespeed
    image: blueapple/ngx-pagespeed-alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./cache/ngx_pagespeed:/var/cache/ngx_pagespeed
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
